[build-system]
requires = [
    "setuptools",
    "wheel",
]
[tool.black]
line-length = 120

[tool.isort]
known_first_party = []
profile = "black"
force_sort_within_sections = "False"
order_by_type = "False"
skip = [".md", ".json", ".gitignore"]
skip_glob = ["docs/*", "test/*"]
